### PR TITLE
Updated Python 2.0 code to Python 3.0

### PR DESCRIPTION
**Pull request by shivaylamba**
I have updated the old Python 2.0 Code to Python 3.0, for example changing the syntax of the print statement to print command.

### CODE REVIEW

**Comment by shivaylamba** [comment]
@JustinGOSSES  Could you review the changes?

**Review by himanshu010 — CHANGES_REQUESTED** [review]
please review that all the numerical value that are required in integer format have a specified int keyword before them otherwise it will be a total mess to deal with in python 3.0

**Comment by christopherburke** [comment]
I have tested these changes and approve them to be merged.  However, I would suggest, that a release with original python 2.0 code be made before these changes are merged.  I do not believe I have any merging power for this repository anymore.

**Comment by JeffLCoughlin** [comment]
@christopherburke , I appear to be able to merge the pull request.  What action should I take to "release with original python 2.0 code" before doing so?

**Comment by christopherburke** [comment]
Thanks for looking into it Jeff.  Releases on Github are just a way to identify a particular version release of the code.  So, you can do a series of commits, and then once you've reached a stable code that has the features you want for the end-users to pay attention to you can 'make a release'.

I recommend we set the original code as a release v1.0 with a description that indicates that it was the original python 2.7 based code to generate the figures and support the KSCI-19109-002
https://ui.adsabs.harvard.edu/abs/2017ksci.rept...17B/abstract
and copy some of the description lines from the README

In order to add a release to the project, go to the project page there are a series of links near the top that show '# commits',  '# branches', '# packages', '# releases', etc.
Select the 'release' link, and it will bring you to a page with a button 'Draft a new release' top right.
That will bring up another page where you can enter 'v1.0' in the 'tag version' box.  Enter a title in the title box 'Original Python 2.7 Initial Release' and the description along the lines of above.
Complete the release, by selecting 'Publish Release' button.
Let me know if you have questions.

After the release is done, then I would merge this code to master with a commit message along the lines of 'Python 3 support Only - No Functional Changes'

**Comment by JeffLCoughlin** [comment]
Got it. Should all be done. Let me know if anything else to do. Thanks for the instructions; had never used the release feature before, that is handy!

**Pull request merged**
